# this workflow using github actions to build a binary exe file for windows users


name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: 安装Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 打包 EXE
        run: |
          pip install pyinstaller
          pyinstaller -F main.py -n Onekey_${{ github.sha }}

      - name: 发布 Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./publish/changeLog.md
          prerelease: false
          draft: false
          tag_name: 12.1
          files: |
            dist/Onekey_${{ github.sha }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
